/* func_ov245_020cfc14 -- ov245's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * The "nothing queued" case RETURNS outright (a predicated `popeq`).
 *
 * Source case order: 0, 1, 2, 4, 5, 3.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

/* Partial AiState, fields from STRUCTS.md; pads are not claims about the object. */
struct AiState {
    unsigned char pad000[0x1ae];
    unsigned short flags1ae;      /* 0x1ae */
    unsigned char pad1b0[0x16];
    signed char currentAction;    /* 0x1c6 */
    signed char pendingAction;    /* 0x1c7 */
};

extern void func_0203c634(int self, int slot, void (*cb)(void));
extern void func_ov245_020cfdec(void);
extern void func_ov245_020cfe58(void);
extern void func_ov245_020cfff4(void);
extern void func_ov245_020d00bc(void);
extern void func_ov245_020d0664(void);
extern void func_ov245_020d0698(void);

void func_ov245_020cfc14(int self) {
    int *ctx;

    ctx = *(int **)(self + 4);
    if (((struct AiState *)(ctx[0]))->pendingAction == -1) {
        return;
    }

    ((struct AiState *)(ctx[0]))->currentAction = ((struct AiState *)(ctx[0]))->pendingAction;
    ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0xc0;
    ((struct AiState *)(ctx[0]))->flags1ae &= ~3;
    ((B8 *)(*(int *)(ctx[0] + 0x388) + 8))->f |= 1;

    switch (((struct AiState *)(ctx[0]))->currentAction) {
    case 0:
        func_0203c634(self, 1, func_ov245_020cfdec);
        break;
    case 1:
        func_0203c634(self, 1, func_ov245_020cfe58);
        break;
    case 2:
        func_0203c634(self, 1, func_ov245_020cfff4);
        break;
    case 4:
        func_0203c634(self, 1, func_ov245_020d00bc);
        break;
    case 5:
        func_0203c634(self, 1, func_ov245_020d0664);
        break;
    case 3:
        func_0203c634(self, 1, func_ov245_020d0698);
        break;
    }

    ((struct AiState *)(ctx[0]))->pendingAction = -1;
}
