/* func_ov125_020ccb24 -- ov125's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * Source case order: 0, 1, 2, 8, 3, 4, 5, 6, 7, 9.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

/* Partial AiState, fields from STRUCTS.md; pads are not claims about the object. */
struct AiState {
    unsigned char pad000[0x60];
    unsigned short flags60;       /* 0x060 */
    unsigned char pad062[0x14c];
    unsigned short flags1ae;      /* 0x1ae */
    unsigned char pad1b0[0x16];
    signed char currentAction;    /* 0x1c6 */
    signed char pendingAction;    /* 0x1c7 */
};

extern void func_0203c634(int self, int slot, void (*cb)(void));
extern void func_ov125_020ccd64(void);
extern void func_ov125_020cce48(void);
extern void func_ov125_020cd04c(void);
extern void func_ov125_020cda84(void);
extern void func_ov125_020cdc00(void);
extern void func_ov125_020cd248(void);
extern void func_ov125_020cd7ec(void);
extern void func_ov125_020cdcc8(void);
extern void func_ov125_020cdfd8(void);
extern void func_ov125_020ce344(void);

void func_ov125_020ccb24(int self) {
    int *ctx;
    unsigned short v;

    ctx = *(int **)(self + 4);
    if (((struct AiState *)(ctx[0]))->pendingAction != -1) {
        v = ((struct AiState *)(ctx[0]))->flags60;
        ((struct AiState *)(ctx[0]))->flags60 =
            (unsigned short)((v & ~0xff00)
                             | (((((unsigned int)v << 0x10) >> 0x18 | 0x40) << 0x18) >> 0x10));
        ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0x86;
        ((struct AiState *)(ctx[0]))->flags1ae &= ~9;
        ((B8 *)(*(int *)(ctx[0] + 0x388) + 8))->f |= 1;
        ((struct AiState *)(ctx[0]))->currentAction = ((struct AiState *)(ctx[0]))->pendingAction;

        switch (((struct AiState *)(ctx[0]))->currentAction) {
        case 0:
            func_0203c634(self, 1, func_ov125_020ccd64);
            break;
        case 1:
            func_0203c634(self, 1, func_ov125_020cce48);
            break;
        case 2:
            func_0203c634(self, 1, func_ov125_020cd04c);
            break;
        case 8:
            func_0203c634(self, 1, func_ov125_020cda84);
            break;
        case 3:
            func_0203c634(self, 1, func_ov125_020cdc00);
            break;
        case 4:
            func_0203c634(self, 1, func_ov125_020cd248);
            break;
        case 5:
            func_0203c634(self, 1, func_ov125_020cd7ec);
            break;
        case 6:
            func_0203c634(self, 1, func_ov125_020cdcc8);
            break;
        case 7:
            func_0203c634(self, 1, func_ov125_020cdfd8);
            break;
        case 9:
            func_0203c634(self, 1, func_ov125_020ce344);
            break;
        }
    }

    ((struct AiState *)(ctx[0]))->pendingAction = -1;
}
