/* func_ov247_020d2694 -- ov247's move dispatcher. The plain family shape: -1 at ctx[0]+0x1c7 means
 * nothing queued, the id is copied to +0x1c6 and it is that copy the switch reads, and the slot is
 * cleared on every path.
 *
 * Source case order: 0, 1, 2, 4, 5, 6, 7, 3, 8.
 * That is the body order, and it is what the switch has to say.
 *
 * Generated by tools/genmove.py from the machine code and verified byte-exact. */

typedef struct {
    unsigned short lo : 8;
    unsigned short hi : 8;
} Hw60;

typedef struct {
    unsigned f : 8;
} B8;

/* Partial AiState, fields from STRUCTS.md; pads are not claims about the object. */
struct AiState {
    unsigned char pad000[0x1ae];
    unsigned short flags1ae;      /* 0x1ae */
    unsigned char pad1b0[0x16];
    signed char currentAction;    /* 0x1c6 */
    signed char pendingAction;    /* 0x1c7 */
};

extern void func_0203c634(int self, int slot, void (*cb)(void));
extern void func_ov247_020d28d0(void);
extern void func_ov247_020d29a0(void);
extern void func_ov247_020d2b64(void);
extern void func_ov247_020d2c2c(void);
extern void func_ov247_020d3034(void);
extern void func_ov247_020d3120(void);
extern void func_ov247_020d340c(void);
extern void func_ov247_020d3780(void);
extern void func_ov247_020d3848(void);

void func_ov247_020d2694(int self) {
    int *ctx;

    ctx = *(int **)(self + 4);
    if (((struct AiState *)(ctx[0]))->pendingAction != -1) {
        ((struct AiState *)(ctx[0]))->currentAction = ((struct AiState *)(ctx[0]))->pendingAction;
        ((Hw60 *)(ctx[0] + 0x60))->hi &= ~0xce;
        ((struct AiState *)(ctx[0]))->flags1ae &= ~9;
        ((B8 *)(*(int *)(ctx[0] + 0x384) + 8))->f |= 1;

        switch (((struct AiState *)(ctx[0]))->currentAction) {
        case 0:
            func_0203c634(self, 1, func_ov247_020d28d0);
            break;
        case 1:
            func_0203c634(self, 1, func_ov247_020d29a0);
            break;
        case 2:
            func_0203c634(self, 1, func_ov247_020d2b64);
            break;
        case 4:
            func_0203c634(self, 1, func_ov247_020d2c2c);
            break;
        case 5:
            func_0203c634(self, 1, func_ov247_020d3034);
            break;
        case 6:
            func_0203c634(self, 1, func_ov247_020d3120);
            break;
        case 7:
            func_0203c634(self, 1, func_ov247_020d340c);
            break;
        case 3:
            func_0203c634(self, 1, func_ov247_020d3780);
            break;
        case 8:
            func_0203c634(self, 1, func_ov247_020d3848);
            break;
        }
    }

    ((struct AiState *)(ctx[0]))->pendingAction = -1;
}
